/**
 * Trivia Rumble Elite 🎮 — client
 *
 * Single GLOBAL room. Every player sees the same question at the same time:
 *   slot = floor((now - game.questionStart) / slotDuration)
 *   question = bank[slot % bank.length]
 * Questions rotate continuously (20s each), generated by opencode.ai big-pickle.
 * Speed-based scoring: first correct answer in a slot scores highest.
 * Players + scores persist in Firebase — leaving never deletes them.
 */

import { initDiscord, isDiscord } from "./discord.js";
import { dbRead, dbWrite, dbUpdate, dbDelete, dbWatch } from "./firebase.js";

// ── Constants ────────────────────────────────────────────────────────────────
const SLOT_DURATION = 20000;   // must match worker
const TOP_UP_THRESHOLD = 20;   // request more questions when fewer remain
const LEADERBOARD_SIZE = 20;

// ── State ────────────────────────────────────────────────────────────────────
let me = { id: null, username: "Guest", avatarUrl: "", score: 0 };
let game = null;       // { questionStart, slotDuration, bankLen }
let bank = [];         // array of { question, options, correctAnswer }
let players = {};      // uid → player
let answers = {};      // uid → { answer, at } for current slot
let offset = 0;        // clock offset (server - client)
let currentSlot = -1;
let myAnswer = null;
let hasAnswered = false;
let revealed = false;
let es = null;
let requestingBank = false;
let lastAnswerGain = 0;

const $ = (id) => document.getElementById(id);
const now = () => Date.now() + offset;

function escapeHtml(s) {
  return String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}
function initials(name) {
  return (name || "?").trim().charAt(0).toUpperCase() || "?";
}
function avatarHtml(player, size = 40) {
  const name = escapeHtml(initials(player?.username));
  const style = `width:${size}px;height:${size}px`;
  if (player?.avatarUrl) {
    return `<img class="avatar" style="${style}" src="${escapeHtml(player.avatarUrl)}" alt="" onerror="this.outerHTML='<span class=&quot;avatar avatar-fallback&quot; style=&quot;${style}&quot;>${name}</span>'">`;
  }
  return `<span class="avatar avatar-fallback" style="${style}">${name}</span>`;
}
function bankArray(obj) {
  if (!obj || typeof obj !== "object") return [];
  return Object.keys(obj)
    .sort((a, b) => Number(a) - Number(b))
    .map((k) => obj[k])
    .filter(Boolean);
}
function showScreen(name) {
  ["loading", "error", "game"].forEach((s) => {
    const el = $(`screen-${s}`);
    if (el) el.classList.toggle("hidden", s !== name);
  });
}

// ── Question timing (deterministic, shared by all players) ──────────────────
function currentQuestion() {
  if (!game || !game.questionStart || !bank.length) return null;
  const duration = game.slotDuration || SLOT_DURATION;
  const elapsed = Math.max(0, now() - game.questionStart);
  const slot = Math.floor(elapsed / duration);
  const idx = slot % bank.length;
  const q = bank[idx];
  if (!q) return null;
  return {
    slot,
    index: slot + 1,          // human-friendly "Question #N"
    question: q,
    slotStart: game.questionStart + slot * duration,
    slotEnd: game.questionStart + (slot + 1) * duration,
  };
}

// ── Firebase paths ──────────────────────────────────────────────────────────
const P = "trivia/global";

// ── SSE patching ────────────────────────────────────────────────────────────
function setPath(obj, path, value) {
  const parts = path.split("/").filter(Boolean);
  let cur = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    const key = parts[i];
    if (!cur[key] || typeof cur[key] !== "object") cur[key] = {};
    cur = cur[key];
  }
  const last = parts[parts.length - 1];
  if (value === null || value === undefined) delete cur[last];
  else cur[last] = value;
}

function onPatch(relPath, data) {
  const path = relPath || "/";
  const parts = path.split("/").filter(Boolean);
  const a = parts[0];

  if (a === "game") {
    if (parts.length === 1) game = data && typeof data === "object" ? data : null;
    else {
      game = { ...(game || {}) };
      setPath(game, parts.slice(1).join("/"), data);
    }
  } else if (a === "bank") {
    if (parts.length === 1) {
      bank = bankArray(data);
    } else {
      const key = Number(parts[1]);
      if (!Number.isNaN(key)) {
        if (data === null) {
          bank = bank.filter((_, i) => i !== key);
        } else {
          const nb = bank.slice();
          while (nb.length <= key) nb.push(null);
          nb[key] = data;
          bank = nb;
        }
      }
    }
  } else if (a === "players") {
    if (parts.length === 1) {
      players = data && typeof data === "object" ? data : {};
    } else {
      players = { ...players };
      setPath(players, parts.slice(1).join("/"), data);
    }
  } else if (a === "answers") {
    const slotKey = Number(parts[1]);
    if (slotKey === currentSlot) {
      answers = { ...answers };
      if (parts.length <= 2) {
        answers = data && typeof data === "object" ? data : {};
      } else {
        setPath(answers, parts.slice(2).join("/"), data);
      }
    }
  }
  refresh();
}

// ── Boot: identity ──────────────────────────────────────────────────────────
async function resolveIdentity() {
  const discordInfo = await initDiscord();
  if (discordInfo.user) {
    return {
      id: "u" + discordInfo.user.id,
      username: discordInfo.user.global_name || discordInfo.user.username || "Player",
      avatarUrl: `https://cdn.discordapp.com/avatars/${discordInfo.user.id}/${discordInfo.user.avatar || "0"}.png`,
    };
  }
  // Guest: stable id in localStorage so scores persist across reloads
  let gid = null;
  try {
    gid = localStorage.getItem("tre_guest_id");
  } catch (e) { /* private mode */ }
  if (!gid) {
    gid = "g" + Math.random().toString(36).slice(2, 10);
    try {
      localStorage.setItem("tre_guest_id", gid);
    } catch (e) { /* ignore */ }
  }
  return {
    id: gid,
    username: "Guest " + Math.floor(Math.random() * 1000),
    avatarUrl: "",
  };
}

// ── Sync clock with the worker ──────────────────────────────────────────────
async function syncTime() {
  try {
    const res = await fetch("/api/time");
    if (res.ok) {
      const data = await res.json();
      offset = data.now - Date.now();
      if (data.game && (!game || !game.questionStart)) game = data.game;
    }
  } catch (e) {
    /* keep previous offset */
  }
}

// ── Join (persistent player record) ─────────────────────────────────────────
async function joinGlobal() {
  const existing = await dbRead(`${P}/players/${me.id}`).catch(() => null);
  if (existing && typeof existing === "object") {
    me.score = existing.score || 0;
    await dbUpdate(`${P}/players/${me.id}`, {
      username: me.username,
      avatarUrl: me.avatarUrl,
      online: true,
      lastSeen: Date.now(),
    });
  } else {
    await dbWrite(`${P}/players/${me.id}`, {
      id: me.id,
      username: me.username,
      avatarUrl: me.avatarUrl,
      score: 0,
      online: true,
      lastSeen: Date.now(),
      joinedAt: Date.now(),
    });
  }
  players = (await dbRead(`${P}/players`).catch(() => ({}))) || {};
  me.score = players[me.id]?.score || 0;
}

// ── Bank management ─────────────────────────────────────────────────────────
async function ensureBank() {
  if (requestingBank) return;
  requestingBank = true;
  try {
    const snapshot = await dbRead(`${P}/bank`).catch(() => null);
    bank = bankArray(snapshot);
    if (bank.length >= TOP_UP_THRESHOLD) return;

    const res = await fetch("/api/trivia", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ count: 20 }),
    });
    if (res.ok) {
      const data = await res.json();
      if (data.bankLen) {
        const fresh = await dbRead(`${P}/bank`).catch(() => null);
        bank = bankArray(fresh);
        const g = await dbRead(`${P}/game`).catch(() => null);
        if (g) game = g;
      }
    }
  } catch (e) {
    console.warn("ensureBank failed:", e);
  } finally {
    requestingBank = false;
  }
}

// ── Answering ───────────────────────────────────────────────────────────────
function pointsFor(elapsedMs) {
  // Speed-based: 100 - 5 per second elapsed, min 10. First correct = highest.
  const seconds = elapsedMs / 1000;
  return Math.max(10, Math.floor(100 - seconds * 5));
}

async function handleAnswer(idx, q) {
  if (hasAnswered || !q) return;
  hasAnswered = true;
  myAnswer = idx;
  const at = now();
  const elapsed = Math.max(0, at - q.slotStart);

  // optimistic local update
  answers[me.id] = { answer: idx, at };
  refresh();

  try {
    await dbUpdate(`${P}/answers/${q.slot}/${me.id}`, { answer: idx, at });
  } catch (e) {
    console.warn("answer write failed:", e);
  }

  if (idx === q.question.correctAnswer) {
    const gain = pointsFor(elapsed);
    me.score += gain;
    lastAnswerGain = gain;
    try {
      await dbUpdate(`${P}/players/${me.id}`, { score: me.score, lastSeen: Date.now() });
    } catch (e) {
      console.warn("score write failed:", e);
    }
  } else {
    lastAnswerGain = 0;
  }

  setTimeout(() => {
    revealed = true;
    renderQuestion(q);
  }, 250);
}

// ── Rendering ───────────────────────────────────────────────────────────────
function renderHeader() {
  const el = $("header-me");
  if (!el) return;
  el.innerHTML =
    avatarHtml(me, 28) +
    `<span class="me-name">${escapeHtml(me.username)}</span>` +
    `<span class="me-score">⭐ ${me.score}</span>` +
    `<span class="tag ${isDiscord ? "tag-discord" : "tag-browser"}">${isDiscord ? "DISCORD" : "BROWSER"}</span>`;
}

function renderQuestion(q) {
  const question = q.question;
  $("q-number").textContent = `Question ${q.index}`;
  updateAnsweredCount();

  $("q-text").textContent = question.question;

  $("q-options").innerHTML = question.options
    .map((opt, i) => {
      let cls = "opt-btn";
      if (revealed) {
        if (i === question.correctAnswer) cls += " correct";
        else if (i === myAnswer) cls += " wrong";
        else cls += " dimmed";
      }
      return `<button class="${cls}" data-idx="${i}" ${hasAnswered ? "disabled" : ""}>
        <span class="opt-letter">${String.fromCharCode(65 + i)}</span>
        <span class="opt-text">${escapeHtml(opt)}</span>
      </button>`;
    })
    .join("");

  document.querySelectorAll(".opt-btn").forEach((btn) => {
    btn.onclick = () => handleAnswer(Number(btn.dataset.idx), q);
  });

  const box = $("q-result");
  if (revealed) {
    box.classList.remove("hidden");
    box.classList.toggle("good", myAnswer === question.correctAnswer);
    box.classList.toggle("bad", myAnswer !== question.correctAnswer);
    box.innerHTML =
      myAnswer === question.correctAnswer
        ? `✅ Correct! +${lastAnswerGain} ⚡`
        : myAnswer === -1
          ? `⏰ Time's up! The answer was: ${escapeHtml(question.options[question.correctAnswer])}`
          : `❌ Wrong! The answer was: ${escapeHtml(question.options[question.correctAnswer])}`;
  } else {
    box.classList.add("hidden");
  }
}

function updateAnsweredCount() {
  const answeredCount = Object.keys(answers).length;
  const onlineCount = Math.max(1, Object.values(players).filter((p) => p.online).length);
  const el = $("q-answered");
  if (el) el.textContent = `⚡ ${answeredCount}/${onlineCount} answered`;
}

function renderLeaderboard() {
  const list = Object.values(players)
    .filter((p) => p && (p.score || 0) > 0)
    .sort((a, b) => (b.score || 0) - (a.score || 0))
    .slice(0, LEADERBOARD_SIZE);

  const el = $("lb-list");
  if (!el) return;
  el.innerHTML = list.length
    ? list
        .map((p, i) => {
          const rank = i + 1;
          const medal = rank === 1 ? "🥇" : rank === 2 ? "🥈" : rank === 3 ? "🥉" : `<span class="rank-num">${rank}</span>`;
          return `
          <div class="lb-row ${p.id === me.id ? "me" : ""} ${rank === 1 ? "first" : ""}">
            <span class="lb-rank">${medal}</span>
            ${avatarHtml(p, 34)}
            <span class="lb-name">${escapeHtml(p.username)}</span>
            ${p.online ? '<span class="dot online" title="online"></span>' : '<span class="dot" title="offline"></span>'}
            <span class="lb-score">${p.score || 0}</span>
          </div>`;
        })
        .join("")
    : '<p class="muted center">No scores yet — be the first! 🏆</p>';

  const mine = players[me.id];
  const myRank = Object.values(players).filter((p) => (p?.score || 0) > (mine?.score || 0)).length + 1;
  const rankEl = $("my-rank");
  if (rankEl) rankEl.textContent = `Your rank: #${myRank} · ⭐ ${mine?.score || 0} pts`;
}

function refresh() {
  renderHeader();
  renderLeaderboard();
  const gameScreen = $("screen-game");
  if (gameScreen && !gameScreen.classList.contains("hidden")) {
    updateAnsweredCount();
  }
}

function showError(msg) {
  $("error-msg").textContent = msg;
  showScreen("error");
}

// ── Presence ────────────────────────────────────────────────────────────────
function startPresence() {
  const beat = async () => {
    try {
      await dbUpdate(`${P}/players/${me.id}`, {
        online: document.visibilityState !== "hidden",
        lastSeen: Date.now(),
      });
    } catch (e) { /* ignore */ }
  };
  beat();
  setInterval(beat, 30000);
  document.addEventListener("visibilitychange", beat);
  window.addEventListener("beforeunload", () => {
    try {
      dbUpdate(`${P}/players/${me.id}`, { online: false, lastSeen: Date.now() });
    } catch (e) { /* ignore */ }
  });
}

// ── Main loop ───────────────────────────────────────────────────────────────
async function loadSlotAnswers(slot) {
  const data = await dbRead(`${P}/answers/${slot}`).catch(() => null);
  answers = data && typeof data === "object" ? data : {};
  refresh();
}

function maybeTopUp(q) {
  const remaining = bank.length - (q.slot % bank.length);
  if (remaining < TOP_UP_THRESHOLD && !requestingBank) {
    ensureBank();
  }
}

function tick() {
  const q = currentQuestion();
  if (!q) {
    showScreen("loading");
    return;
  }

  // New question slot → reset local state
  if (q.slot !== currentSlot) {
    currentSlot = q.slot;
    myAnswer = null;
    hasAnswered = false;
    revealed = false;
    answers = {};
    loadSlotAnswers(q.slot);
    maybeTopUp(q);
    renderQuestion(q);
  }

  // Timer bar
  const remaining = Math.max(0, q.slotEnd - now());
  const pct = (remaining / SLOT_DURATION) * 100;
  const bar = $("q-progress");
  if (bar) {
    bar.style.width = pct + "%";
    bar.classList.toggle("danger", remaining < 5000);
  }
  const tEl = $("q-time");
  if (tEl) {
    tEl.textContent = Math.ceil(remaining / 1000) + "s";
    tEl.classList.toggle("danger", remaining < 5000);
  }

  // Time up → auto-reveal
  if (remaining <= 0 && !hasAnswered) {
    myAnswer = -1;
    hasAnswered = true;
    revealed = true;
    renderQuestion(q);
  }

  showScreen("game");
}

// ── Boot ─────────────────────────────────────────────────────────────────────
async function boot() {
  showScreen("loading");

  // OAuth popup (Discord web-client authorize): show confirmation, don't boot.
  if (window.opener && !window.opener.closed) {
    $("screen-loading").classList.add("hidden");
    $("screen-error").classList.add("hidden");
    const gs = $("screen-game");
    gs.classList.remove("hidden");
    gs.innerHTML = `<div class="card center-box" style="min-height:40vh">
      <div style="font-size:52px">✅</div>
      <h2>You're connected!</h2>
      <p class="muted">Return to the game — your Discord name is ready.</p>
    </div>`;
    return;
  }

  const identity = await resolveIdentity();
  me = identity;
  renderHeader();

  // Every step is independently resilient — one failure must never brick the
  // whole game. Firebase writes failing (sandbox restrictions, rate limits)
  // degrade to local-only play instead of an error screen.
  const fails = [];
  await syncTime();
  try {
    await joinGlobal();
  } catch (err) {
    fails.push("join: " + (err.message || err));
  }
  await ensureBank();
  subscribe();
  startPresence();

  setInterval(tick, 100);
  setInterval(syncTime, 5 * 60 * 1000);
  $("btn-retry").onclick = () => window.location.reload();

  if (fails.length) {
    console.warn("Degraded boot:", fails);
    // still playable — local mode with the live question stream
  }
}

function subscribe() {
  es = dbWatch(P, onPatch);
  es.onerror = () => {
    /* EventSource auto-reconnects */
  };
}

boot();
